version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - run:
            name: "Show node and yarn versions"
            command: |
              node --version
              yarn --version
      - checkout
      - run: yarn install
      - run: yarn run test

workflows:
  version: 2
  test:
    jobs:
      - test
